version: '2'
services:
    rails:
        build: ./server
        volumes:
            - ./server:/var/www/API
            - database:/var/db
        ports:
            - '8080:8080'
    node:
        image: nginx:stable-alpine
        volumes:
            - ./client/dist:/usr/share/nginx/html
        ports:
            - '8000:80'
volumes:
    database:
        driver: local
